### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by vtsingaras** [cloudregistry/eppy#13]
Hi! Are you planning on maintaining a Py2/3 version of your package? The one downloaded from pypi is not python 3 compatible.

**Comment by wil** [comment]
Hi Vyronas, there is a py3 branch which uses `six` to support both versions. I'll look into merging that and making a release onto PyPI in the next few days.

**Comment by wil** [comment]
Hello Vyronas, I have released version 0.9.1 onto PyPI. This should be compatible with Python 3.
Would you like to give it a try?
```
pip install -U EPP
```

**Comment by wil** [comment]
Closing this. Please let us know if you have any issues with the package.
