### ISSUE TITLE
eppy depends on backports.ssl_match_hostname

### ISSUE THREAD

**Issue by JanKlopper** [cloudregistry/eppy#8]
Your pip based package uses backports.ssl_match_hostname but does not install it as a dependency. It'd be better if that dependency was automatically resolved by setting it in the install_requieres list.

**Comment by wil** [comment]
Thanks for reporting this.

I have just uploaded version 0.8.1 to PyPI, which contains the fix you suggested (which was actually reported by @fnordahl in #7)

Please let me know if it doesn't work for you.
